#!/bin/sh

# Cleanup old build artifacts
rm -rf obj_dir
rm -f *.vcd

# Run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace f1_fsm.sv clktick.sv f1_fsm_with_clktick.sv --exe f1_fsm_with_clktick_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_fsm.mk Vf1_fsm

# Run executable simulation file
echo "\nRunning simulation"
obj_dir/Vf1_fsm
echo "\nSimulation completed"
